@VasiukovSite.BackEndNet.API_HostAddress = http://localhost:61096

GET {{VasiukovSite.BackEndNet.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{VasiukovSite.BackEndNet.API_HostAddress}}/api/profile/v1/profile/profileData
Accept: application/json

###
